### ISSUE TITLE
Update installation path

### ISSUE THREAD

**Issue by sandstrom** [vvanholl/elasticsearch-consul-discovery#13]
Would be better to use github as the source:
https://github.com/vvanholl/elasticsearch-consul-discovery/releases/download/6.3.0.1/elasticsearch-consul-discovery-6.3.0.1.zip

Instead of the current url, under a to most unknown hostname (distfiles.compuscene.net).

**Comment by asteny** [comment]
https://github.com/vvanholl/elasticsearch-consul-discovery/pull/15
