### ISSUE TITLE
deef31ca4293e577d9d9f15b8fddbb5156a214c8 was a breaking change

### ISSUE THREAD

**Issue by dropje86** [vvanholl/elasticsearch-consul-discovery#7]
@claytonsilva broke defaults with commit: https://github.com/vvanholl/elasticsearch-consul-discovery/commit/deef31ca4293e577d9d9f15b8fddbb5156a214c8

broke default behavior because the URL scheme has been removed. If I don't specify `CONSUL_LOCALWSHOST` I get the following exception:

```
[2017-08-23T08:46:52,515][ERROR][o.e.d.c.ConsulUnicastHostsProvider] [client_2863a7f8-98e8-b13d-d565-74c1432d8e65_worker007_zone1] Failed to discover nodes, failed in making consul based discovery
java.net.MalformedURLException: unknown protocol: localhost
```

**Comment by claytonsilva** [comment]
hmmm, i will fix change default value.
